export const palette = {
  gold: 'var(--color-gold)',
  goldHover: 'var(--color-gold-hover)',
  goldMuted: 'var(--color-gold-muted)',
  copper: 'var(--color-copper)',
  copperHover: 'var(--color-copper-hover)',
  copperMuted: 'var(--color-copper-muted)',
  deepBlue: 'var(--color-deep-blue)',
  deepBlueLight: 'var(--color-deep-blue-light)',
  primary: 'var(--color-primary)',
  primaryHover: 'var(--color-primary-hover)',
  secondary: 'var(--color-secondary)',
  accent: 'var(--color-accent)',
  accentHover: 'var(--color-accent-hover)',
  accentMuted: 'var(--color-accent-muted)',
  background: 'var(--color-background)',
  backgroundDark: 'var(--color-background-dark)',
  surface: 'var(--color-surface)',
  surfaceHover: 'var(--color-surface-hover)',
  surfaceElevated: 'var(--color-surface-elevated)',
  border: 'var(--color-border)',
  borderStrong: 'var(--color-border-strong)',
  borderSubtle: 'var(--color-border-subtle)',
  text: 'var(--color-text)',
  textMuted: 'var(--color-text-muted)',
  textGold: 'var(--color-text-gold)',
  success: 'var(--color-success)',
  successSoft: 'var(--color-success-soft)',
  warning: 'var(--color-warning)',
  warningSoft: 'var(--color-warning-soft)',
  danger: 'var(--color-danger)',
  dangerSoft: 'var(--color-danger-soft)',
  info: 'var(--color-info)',
  infoSoft: 'var(--color-info-soft)',
  overlay: 'var(--color-overlay)',
  shadow: 'var(--shadow-gold)',
  shadowStrong: 'var(--shadow-gold-strong)',
};

export type PaletteToken = keyof typeof palette;

export const themeColor = (token: PaletteToken): string => palette[token];
